site_name: 'Pymia'
copyright: Copyright &copy; 2019 - 2020 pymia
theme:
  custom_dir: overrides
  icon:
    logo: material/bookshelf
  font:
    text: Noto Sans TC
  language: zh-TW
  name: material
  palette:
    primary: teal
    scheme: preference
  features:
    - navigation.instant
nav:
  - Home: README.md
  - Linux:
      - Network: mlops/introduction.md
  - Other: others.md
  - Talks: talks.md
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/technologynote
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/technologynoteniu
    - icon: fontawesome/brands/github
      link: https://github.com/technologynoteniu

markdown_extensions:
  - toc:
      permalink: true
