site_name: 'Pymia'
copyright: Copyright &copy; 2019 - 2020 pymia
theme:
  custom_dir: overrides
  icon:
    logo: material/bookmark-outline
  font:
    text: Noto Sans TC
  language: zh-TW
  name: material
  palette:
    primary: blue grey
    scheme: preference
  features:
    - navigation.instant
nav:
  - Home: README.md
  - Linux:
      - Network: mlops/introduction.md
  - Other: others.md
  - Talks: talks.md
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/MLOps_News
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/bymiachang.tw
    - icon: fontawesome/brands/github
      link: https://github.com/pymia
    - icon: fontawesome/brands/medium
      link: https://medium.com/@Mia.Chang

markdown_extensions:
  - toc:
      permalink: true
